In [4]:
import numpy as np

np.ones([2,2])


array([[1., 1.],
       [1., 1.]])

In [12]:
np.empty([2,2],dtype=int)                 #Random Values

array([[-1717811824,         642],
       [          0,           0]])

In [17]:
b=np.zeros(10,dtype=int)
b[5]=1

print(b)

[0 0 0 0 0 1 0 0 0 0]


In [26]:
b=np.linspace(2,10,endpoint=False)
b

array([2.  , 2.16, 2.32, 2.48, 2.64, 2.8 , 2.96, 3.12, 3.28, 3.44, 3.6 ,
       3.76, 3.92, 4.08, 4.24, 4.4 , 4.56, 4.72, 4.88, 5.04, 5.2 , 5.36,
       5.52, 5.68, 5.84, 6.  , 6.16, 6.32, 6.48, 6.64, 6.8 , 6.96, 7.12,
       7.28, 7.44, 7.6 , 7.76, 7.92, 8.08, 8.24, 8.4 , 8.56, 8.72, 8.88,
       9.04, 9.2 , 9.36, 9.52, 9.68, 9.84])

In [32]:
b.shape                 #50 Rows,1 Column

(50,)

In [38]:
np.random.rand(2,3)

array([[0.06223516, 0.01761592, 0.41683849],
       [0.26025599, 0.45939592, 0.417966  ]])

In [40]:
np.random.rand(5)*10

array([2.20426305, 5.61907654, 1.0107357 , 4.99897526, 2.36260509])

In [41]:
np.random.randint(5,size=[2,3])

array([[3, 4, 0],
       [0, 0, 1]])

In [45]:
#np.random.randint(10, 4)            s>e
np.random.randint(4,10)                



4

In [48]:
li=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
arr = np.array(li)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [49]:
print(li[2][1:3])
print(arr[2][1:3])

[10, 11]
[10 11]


In [51]:
print(li[1:3][2])
print(arr[1:3][2])


IndexError: list index out of range

In [53]:
print(li[1:3][:])
print(arr[1:3][:])

[[5, 6, 7, 8], [9, 10, 11, 12]]
[[ 5  6  7  8]
 [ 9 10 11 12]]


In [54]:
print(arr[1:3,:1])

[[5]
 [9]]


In [57]:
arr = np.arange(1,21)
arr =arr.reshape(4,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [60]:
arr = np.arange(1,17)            #end not included
arr =arr.reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [71]:
b = np.random.randint(20,size=9)
b

array([14,  9,  6, 16, 19, 11,  0,  5,  1])

In [72]:
b[b>10]

array([14, 16, 19, 11])

In [73]:
ind = np.where(b>10)
ind

(array([0, 3, 4, 5], dtype=int64),)

In [74]:
ind = np.where((b>10) & (b<16))
ind

(array([0, 5], dtype=int64),)

In [75]:
print(b)
b[:3] = 100
b

[14  9  6 16 19 11  0  5  1]


array([100, 100, 100,  16,  19,  11,   0,   5,   1])

In [94]:
a=[1,2,0,0,4,0]
b=np.array(a)
arr=np.where(b > 0)

print(arr)


for i in arr:
    print(i,end=" ")
    
print()

for i in arr:
    print(*i,end=" ")
arr

(array([0, 1, 4], dtype=int64),)
[0 1 4] 
0 1 4 

(array([0, 1, 4], dtype=int64),)

In [86]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [95]:
print(a)
print(*a)

for i in a:
    print(i,end=" ")
    
    
a

[1, 2, 0, 0, 4, 0]
1 2 0 0 4 0
1 2 0 0 4 0 

[1, 2, 0, 0, 4, 0]

In [100]:
a=np.array(a)
print(a)
a.max()
a[a.argmax()] = -1
print(a)

[1 2 0 0 4 0]
[ 1  2  0  0 -1  0]


Given a 1D array, negate all elements which are between 3 and 8

In [110]:
#GQ
a = np.arange(10)
print(a)

a[np.where((a>=3) & (a<=8))]*=(-1)

print(a)



[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


In [115]:
a = np.random.randint(1,20,size=20).reshape([4,5])
a

array([[15,  5, 14, 11,  6],
       [12, 18,  3,  4, 16],
       [13, 11,  8, 13,  1],
       [14,  3,  1, 18,  7]])

In [116]:
a>10

array([[ True, False,  True,  True, False],
       [ True,  True, False, False,  True],
       [ True,  True, False,  True, False],
       [ True, False, False,  True, False]])

In [117]:
a[a>10]                        #1D Array

array([15, 14, 11, 12, 18, 16, 13, 11, 13, 14, 18])

In [146]:
a = np.random.randint(1,20,size=20).reshape([4,5])
a[2][3] = 13
a

array([[ 5,  6,  2, 12, 19],
       [ 8, 19,  8, 17,  2],
       [ 9, 12,  6, 13,  1],
       [18, 16, 14,  9, 12]])

Subsituting  All 13 in fourth Column by -1

In [147]:
#GQ
print(a)

bool_arr = (a[:,3]==13)
print(bool_arr)

a[bool_arr, 3] = -1
print(a)


[[ 5  6  2 12 19]
 [ 8 19  8 17  2]
 [ 9 12  6 13  1]
 [18 16 14  9 12]]
[False False  True False]
[[ 5  6  2 12 19]
 [ 8 19  8 17  2]
 [ 9 12  6 -1  1]
 [18 16 14  9 12]]
