In [1]:
import numpy as np
from sklearn import preprocessing

In [2]:
X = np.array([[-1,-1,2],[2,0,0],[0,1,-1]])                   #X_train 

In [3]:
X_Scaled = preprocessing.scale(X)                        #Use float to avoid these warnings

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)


In [4]:
X_Scaled

array([[-1.06904497, -1.22474487,  1.33630621],
       [ 1.33630621,  0.        , -0.26726124],
       [-0.26726124,  1.22474487, -1.06904497]])

In [5]:
X_Scaled.mean(axis=0)

array([3.70074342e-17, 0.00000000e+00, 0.00000000e+00])

In [6]:
X_Scaled.std(axis=0)

array([1., 1., 1.])

In [7]:
#But How to Scale X_test to the Same Parameters?

In [8]:
scaler = preprocessing.StandardScaler()
scaler.fit(X)                                    #X not Normalized yet

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


StandardScaler(copy=True, with_mean=True, with_std=True)

In [9]:
scaler.transform(X)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[-1.06904497, -1.22474487,  1.33630621],
       [ 1.33630621,  0.        , -0.26726124],
       [-0.26726124,  1.22474487, -1.06904497]])

In [10]:
X_test = [[2,1,-1],[1,2,3]]                         #Mean != 0         #Not Normalized on this data
scaler.transform(X_test)                            #This data is normalized on the scale of prev data

array([[ 1.33630621,  1.22474487, -1.06904497],
       [ 0.53452248,  2.44948974,  2.13808994]])

In [11]:
preprocessing.scale(X_test)                 #Mean = 0

array([[ 1., -1., -1.],
       [-1.,  1.,  1.]])