In [1]:
import numpy as np

In [2]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])                 
y = np.array([[0,0,0,1]]).T 

In [3]:
def sig(z):
    return 1/(1+np.exp(-z))

def derivativeSig(z):
    return sig(z)*(1-sig(z))

In [7]:
weights = 2*np.random.random((2,1))  - 1                    
bias = 2*np.random.random(1)  - 1     
lr = 0.01
weights , bias

(array([[-0.7237468 ],
        [ 0.68302267]]), array([-0.81033681]))

In [ ]:
output0 = X                                                  #Dont Run Next 5 Cells
output = sig( np.dot( output0,weights) + bias )                 

In [ ]:
#Finding First two terms of the Derivative
#First two terms of Derivative Same for all weights(only 1 layer) - Dependent only on output -> Only 1 (y_pred)
first_term = output - y                                       #y_pred - y_act

input_for_last_layer = np.dot(output0,weights) + bias
second_term = derivativeSig(input_for_last_layer)                      #Oj(1-Oj)      #output(1-output)

first_two_terms = first_term * second_term               
 
#print(first_term.shape)
#print(input_for_last_layer.shape)
#print(second_term.shape)
#print(first_two_terms.shape)               #All (4,1)

#second_term == output*(1-output)


In [ ]:
changes = np.array([ [0.0],[0.0] ])            #To update Weights
print(changes)

In [ ]:
for i in range(2):
    for j in range(4):
        changes[i][0] += first_two_terms[j][0] * output0[j][i]             #Derivative
        
weights = weights - (lr * changes)                   #Gradient Descent

In [ ]:
bias_change = 0.0
for j in range(4):                                       #Only 1 bias so no outer loop
    bias_change += first_two_terms[j][0] * 1
    
bias = bias - (lr * bias_change)


In [ ]:
#Gradient Descent Currently Only Running Once. Should  be Iterated
#Put above 5 cells in a loop

In [10]:
for iter in range(10000):
    output0 = X
    output = sig( np.dot( output0,weights) + bias )  
    
    first_term = output - y

    input_for_last_layer = np.dot(output0,weights) + bias
    second_term = derivativeSig(input_for_last_layer)                   

    first_two_terms = first_term * second_term               
    
    changes = np.array([ [0.0],[0.0] ])
    
    for i in range(2):
        for j in range(4):
            changes[i][0] += first_two_terms[j][0] * output0[j][i]          
    weights = weights - (lr * changes)
    
    
    bias_change = 0.0
    for j in range(4):                    
        bias_change += first_two_terms[j][0] * 1
    bias = bias - (lr * bias_change)
    
    

In [18]:
print(weights,end='\n\n')
print(bias,end='\n\n')
print(output)

[[3.50647889]
 [3.50664173]]

[-5.36855669]

[[0.00463966]
 [0.13448357]
 [0.13446462]
 [0.8381506 ]]


In [19]:
#Vectorised Implementation
for iter in range(10000):
    output0 = X
    output = sig( np.dot( output0,weights) + bias )  
    
    first_term = output - y

    input_for_last_layer = np.dot(output0,weights) + bias
    second_term = derivativeSig(input_for_last_layer)                   

    first_two_terms = first_term * second_term               
    
    changes = np.dot(output0.T,first_two_terms) 
    weights = weights - (lr * changes)

    
    bias_change = np.sum(first_two_terms)
    bias = bias - (lr * bias_change)
    